In [1]:
import tensorflow as tf

** Note that the python syntax for list and tuple are different when it handles None (Null value) **

In [2]:
print([None])

[None]


In [3]:
[None] is None

False

In [5]:
print((None))

None


In [6]:
(None) is None

True

In [7]:
sess = tf.InteractiveSession()

In [12]:
tf.zeros(shape=[2,3]).eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [13]:
tf.zeros(shape=(2,3)).eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

** the above is fine because the shape is propery defined **

*** However the issue is with defining placeholders, for example, with unknown batch size where None is used ***

https://github.com/tensorflow/tensorflow/issues/2834

In [15]:
import numpy as np

In [16]:
# with tuple shape
ph = tf.placeholder(tf.int32, (None))
op = 2 * ph
x = np.random.randint(0, 9, (5, 5))
## not we are feeding a dict of rank 1 with a numpy array value of rank 2
sess.run(op, feed_dict={ph: x}) 

array([[ 4, 16,  4, 10, 10],
       [ 4,  8,  8,  0,  8],
       [10,  0, 16,  4,  2],
       [ 0, 10,  2,  2,  4],
       [16,  4, 12, 16,  4]], dtype=int32)

In [18]:
# with list shape
ph = tf.placeholder(tf.int32, [None])
op = 2 * ph
x = np.random.randint(0, 9, (5, 5))
## not we are feeding a dict of rank 1 with a numpy array value of rank 2
sess.run(op, feed_dict={ph: x})  # this will cause an error

ValueError: Cannot feed value of shape (5, 5) for Tensor 'Placeholder_3:0', which has shape '(?,)'