In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.0.1'

In [6]:
sess = tf.InteractiveSession()

In [4]:
a = tf.zeros((2,3), dtype=tf.float64)

**Some constants**

In [7]:
a.eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
b = tf.zeros_like(a)
b.eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
c = tf.ones_like(a)
c.eval()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Range

In [11]:
tf.range(10).eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Random operations

In [13]:
tf.random_normal((2,3)).eval()

array([[ 0.14810468, -0.46803284, -0.74696004],
       [-0.30281299, -0.35296565, -0.83904666]], dtype=float32)

In [21]:
d = tf.random_normal((20,20))

In [35]:
tf.random_crop(d, [3,5]).eval()

array([[ 1.6115669 , -0.68611693, -0.55274516,  0.34792793, -1.59224963],
       [-1.56971157, -0.27630323,  0.83530986,  1.11341357, -0.15900797],
       [ 0.02077354,  0.49652743, -0.486635  ,  1.99717104, -0.7500236 ]], dtype=float32)

Operations

In [36]:
x = tf.constant([3, 6])
y = tf.constant([2, 2])

In [37]:
tf.add(x, y).eval()

array([5, 8], dtype=int32)

In [38]:
tf.add_n([x, y, y]).eval()

array([ 7, 10], dtype=int32)

In [39]:
tf.multiply(x, y).eval()

array([ 6, 12], dtype=int32)

In [41]:
# tf.matmul(x, y) error matrix dim dont agree

In [42]:
tf.div(x, y).eval()

array([1, 3], dtype=int32)

In [43]:
tf.mod(x, y).eval()

array([1, 0], dtype=int32)

Tensorflow takes python native types: bool, int, float, strings

In [45]:
t_0 = 19 
tf.zeros_like(t_0).eval()

0

In [47]:
t_1 = ['apple', 'peach', 'banana']
tf.zeros_like(t_1).eval()

array([b'', b'', b''], dtype=object)

In [49]:
# tf.ones_like(t_1).eval() # error

TypeError: Expected string, got 1 of type 'int' instead.