In [1]:
import tensorflow as tf

In [7]:
rand1 = tf.truncated_normal(shape=[2,3])
rand2 = tf.truncated_normal(shape=[2,3])

In [8]:
op1 = rand1 + rand2
op2 = rand1 + rand2

In [11]:
init = tf.global_variables_initializer()

In [12]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(op1))
    print(sess.run(op2))

[[-2.07228327 -0.5256691   0.48887879]
 [-0.09556645  1.01404095  0.02156116]]
[[ 0.91713607  1.12895238  1.59771621]
 [-0.07578194  1.40823698  0.09873536]]


** Note that above each call to run, runs the computational graph and as a resut, we get different random realization for rand1 and rand2 for each of the runs. There is no <font color="red"> state </font> **

<font color="green"> To introduce state across runs, we need to use variables </font>

In [13]:
var1 = tf.Variable(rand1)
var2 = tf.Variable(rand2)

In [14]:
op3 = var1 + var2
op4 = var1 + var2

In [15]:
init2 = tf.global_variables_initializer()

In [16]:
with tf.Session() as sess:
    sess.run(init2)
    print(sess.run(op3))
    print(sess.run(op4))

[[ 2.3433044   0.76801151 -1.97985017]
 [ 0.22219297 -0.40567756 -0.3963542 ]]
[[ 2.3433044   0.76801151 -1.97985017]
 [ 0.22219297 -0.40567756 -0.3963542 ]]


** Observe the stateful behaviour above **

### Initializing varialbes from other variables

In [17]:
# note that this can be dangerous because if var is not inited as a
# part of session, we might be trouble

var3 = tf.Variable(2 * var1) 


In [19]:
# so the safe option will be
var4 = tf.Variable(2 * var1.initialized_value())

In [29]:
var5 = 2 * var1

In [32]:
with tf.Session() as sess:
    
    # both varwill be error because var1 is not inited
    # sess.run(tf.variables_initializer([var3])) 
    # sess.run(tf.variables_initializer([var5]))
    
    sess.run(tf.variables_initializer([var4]))
    print(sess.run(var4))

AttributeError: 'Tensor' object has no attribute 'initializer'